name: Build and deploy app
on:
  push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.5

      - name: Build Deno SPA
        run: |
          deno install --allow-scripts --reload
          VITE_API_URL=https://api.nanoapi.io deno task build:app

      - name: Deploy to Firebase
        # only deploy on main branch
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "./packages/app"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANOAPI_INFRA_PRODUCTION }}
          channelId: live
          projectId: nanoapi-infra-production
